# =============================================================================
#  VeldraDB → Unity Integration Script
#  Usage:
#    .\install_unity.ps1 -UnityProjectPath "C:\MyGame"
#
#  What it does:
#    1. Builds veldra.dll via CMake (Release, x64)
#    2. Copies veldra.dll     → <project>/Assets/Plugins/VeldraDB/
#    3. Copies VeldraDB.cs    → <project>/Assets/Plugins/VeldraDB/
#    4. Copies VeldraDBUnity.cs (MonoBehaviour wrapper) → same folder
#    5. Creates an asmdef so the plugin is isolated
# =============================================================================

param(
    [Parameter(Mandatory=$true)]
    [string]$UnityProjectPath,

    [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"

# ── Paths ────────────────────────────────────────────────────────────────────
$ScriptDir    = Split-Path -Parent $MyInvocation.MyCommand.Path
$VeldraRoot   = Split-Path -Parent $ScriptDir          # repo root
$BuildDir     = Join-Path $VeldraRoot "build_unity"
$PluginDest   = Join-Path $UnityProjectPath "Assets\Plugins\VeldraDB"
$NativeDest   = Join-Path $PluginDest "Native\x86_64"

# ── 1. Build veldra.dll ───────────────────────────────────────────────────────
if (-not $SkipBuild) {
    Write-Host "`n[VeldraDB] Building native DLL (CMake Release x64)..." -ForegroundColor Cyan

    if (-not (Test-Path $BuildDir)) { New-Item -ItemType Directory -Path $BuildDir | Out-Null }

    Push-Location $BuildDir
    try {
        cmake $VeldraRoot -G "Visual Studio 17 2022" -A x64 | Out-Host
        cmake --build . --config Release --target veldra | Out-Host
    } finally {
        Pop-Location
    }

    $BuiltDll = Join-Path $BuildDir "Release\veldra.dll"
    if (-not (Test-Path $BuiltDll)) {
        # Try MinGW / Makefile layout
        $BuiltDll = Join-Path $BuildDir "veldra.dll"
    }
    if (-not (Test-Path $BuiltDll)) {
        Write-Error "[VeldraDB] Build failed – veldra.dll not found in $BuildDir"
    }
} else {
    Write-Host "`n[VeldraDB] Skipping build (-SkipBuild flag set)." -ForegroundColor Yellow
    # Fall back to pre-built DLL shipped in bindings/c#
    $BuiltDll = Join-Path $VeldraRoot "bindings\c#\veldra.dll"
    if (-not (Test-Path $BuiltDll)) {
        Write-Error "[VeldraDB] Pre-built veldra.dll not found at $BuiltDll. Run without -SkipBuild."
    }
}

# ── 2. Validate Unity project ─────────────────────────────────────────────────
if (-not (Test-Path (Join-Path $UnityProjectPath "Assets"))) {
    Write-Error "[VeldraDB] '$UnityProjectPath' does not look like a Unity project (no Assets folder)."
}

# ── 3. Create destination folders ─────────────────────────────────────────────
Write-Host "[VeldraDB] Creating plugin folders..." -ForegroundColor Cyan
New-Item -ItemType Directory -Path $PluginDest  -Force | Out-Null
New-Item -ItemType Directory -Path $NativeDest  -Force | Out-Null

# ── 4. Copy native DLL ────────────────────────────────────────────────────────
Write-Host "[VeldraDB] Copying veldra.dll → $NativeDest" -ForegroundColor Cyan
Copy-Item -Path $BuiltDll -Destination (Join-Path $NativeDest "veldra.dll") -Force

# ── 5. Copy C# binding ────────────────────────────────────────────────────────
$CsBinding = Join-Path $VeldraRoot "bindings\c#\VeldraDB.cs"
Write-Host "[VeldraDB] Copying VeldraDB.cs → $PluginDest" -ForegroundColor Cyan
Copy-Item -Path $CsBinding -Destination (Join-Path $PluginDest "VeldraDB.cs") -Force

# ── 6. Generate Unity MonoBehaviour wrapper ───────────────────────────────────
$WrapperCs = @'
// VeldraDBManager.cs – Auto-generated by install_unity.ps1
// Drop this component onto any GameObject to access VeldraDB from Unity.
using UnityEngine;
using Veldra;

namespace VeldraDB.Unity
{
    public class VeldraDBManager : MonoBehaviour
    {
        private global::Veldra.VeldraDB _db;

        /// <summary>Singleton access point (optional pattern).</summary>
        public static VeldraDBManager Instance { get; private set; }

        void Awake()
        {
            if (Instance != null && Instance != this) { Destroy(gameObject); return; }
            Instance = this;
            DontDestroyOnLoad(gameObject);

            try
            {
                _db = new global::Veldra.VeldraDB();
                Debug.Log("[VeldraDB] Initialized successfully.");
            }
            catch (System.Exception e)
            {
                Debug.LogError("[VeldraDB] Failed to initialize: " + e.Message);
            }
        }

        /// <summary>Execute a VeldraDB query. Returns the text result or an error message.</summary>
        public string Query(string sql)
        {
            if (_db == null) return "[VeldraDB] Not initialized.";
            try   { return _db.Query(sql); }
            catch (System.Exception e) { return "[VeldraDB] Error: " + e.Message; }
        }

        void OnDestroy()
        {
            _db?.Dispose();
        }
    }
}
'@

$WrapperPath = Join-Path $PluginDest "VeldraDBManager.cs"
Write-Host "[VeldraDB] Writing VeldraDBManager.cs → $PluginDest" -ForegroundColor Cyan
Set-Content -Path $WrapperPath -Value $WrapperCs -Encoding UTF8

# ── 7. Generate .meta stub for the DLL (sets platform + CPU) ─────────────────
$DllMetaPath = Join-Path $NativeDest "veldra.dll.meta"
$DllMeta = @"
fileFormatVersion: 2
guid: $(([System.Guid]::NewGuid()).ToString("N"))
PluginImporter:
  externalObjects: {}
  serializedVersion: 2
  iconMap: {}
  executionOrder: {}
  defineConstraints: []
  isPreloaded: 0
  isOverridable: 0
  isExplicitlyReferenced: 0
  validateReferences: 1
  platformData:
  - first:
      Any:
    second:
      enabled: 0
      settings: {}
  - first:
      Editor: Editor
    second:
      enabled: 0
      settings:
        DefaultValueInitialized: true
  - first:
      Standalone: Win64
    second:
      enabled: 1
      settings:
        CPU: x86_64
  userData:
  assetBundleName:
  assetBundleVariant:
"@
Set-Content -Path $DllMetaPath -Value $DllMeta -Encoding UTF8

# ── 8. Generate Assembly Definition ──────────────────────────────────────────
$AsmdefPath = Join-Path $PluginDest "VeldraDB.asmdef"
$Asmdef = @"
{
    "name": "VeldraDB",
    "rootNamespace": "VeldraDB.Unity",
    "references": [],
    "includePlatforms": [],
    "excludePlatforms": [],
    "allowUnsafeCode": false,
    "overrideReferences": false,
    "precompiledReferences": [],
    "autoReferenced": true,
    "defineConstraints": [],
    "versionDefines": [],
    "noEngineReferences": false
}
"@
Set-Content -Path $AsmdefPath -Value $Asmdef -Encoding UTF8

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host @"

╔══════════════════════════════════════════════════════════╗
║   VeldraDB → Unity integration complete!                ║
╠══════════════════════════════════════════════════════════╣
║  Files installed to:                                    ║
║    $PluginDest
║                                                          ║
║  Next steps:                                             ║
║   1. Open your Unity project (it will reimport assets)  ║
║   2. Add VeldraDBManager component to a GameObject      ║
║   3. Call VeldraDBManager.Instance.Query("SELECT ...")  ║
╚══════════════════════════════════════════════════════════╝
"@ -ForegroundColor Green
